# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c02f3db890d69a744c0317e98d1d3ef45ca164bb5d5e938cf9eb531bfc5236a24ec4c64d0b8075a19d0a2dcba4a975f10d1add44e1033829c4cbfc085751935
  storage_access_key: <%= ENV['STORAGE_ACCESS_KEY']%>
  app_url: "http:localhost:3000"
  storage_access_secret: <%= ENV['STORAGE_ACCESS_SECRET']%> 
  cloud_storage: "google"
  admin_email: <%= ENV['ADMIN_USERNAME']%>
  admin_password: <%= ENV['ADMIN_PASSWORD']%>

test:
  secret_key_base: cef6215cc69a5d16914ad58bca369d012a488c429d16dee0b551d7b7324c293f1aed23e6fb5e100967518569836fd5b4607c0e83d988bce02d87c61cbbc10796
  app_url: "http:localhost:3000"
  storage_access_key: <%= ENV['STORAGE_ACCESS_KEY']%>
  storage_access_secret: <%= ENV['STORAGE_ACCESS_SECRET']%> 
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  storage_access_key: <%= ENV['STORAGE_ACCESS_KEY']%>
  storage_access_secret: <%= ENV['STORAGE_ACCESS_SECRET']%>
  app_url: http://api.yelo.red
  cloud_storage: "google"
  admin_email: <%= ENV['ADMIN_USERNAME']%>
  admin_password: <%= ENV['ADMIN_PASSWORD']%>